os:
  - linux
language: go
sudo: required
go:
  - 1.12.x
dist: trusty
stages:
  - test
  - name: deploy
    if: branch IN (develop) AND type = push
env:
  global:
    - GO111MODULE=on
    - AWS_ACCESS_KEY_ID_AGREEMENT=key_id
    - AWS_SECRET_ACCESS_KEY_AGREEMENT=secret_key
    - AWS_REGION_AGREEMENT=eu-west-1
    - AWS_BUCKET_AGREEMENT=bucket
    - ORDER_INLINE_FORM_URL_MASK=https://checkout.tst.protocol.one/order
jobs:
  include:
    - stage: test
      cache:
        directories:
          - $HOME/gopath/pkg/mod
      install: true
      script:
        - make github-test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      services: docker
      install: true
      script:
        - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
          -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
          p1hub/p1jenkinstrigger
notifications:
  email: false
git:
  submodules: false
